# https://github.com/Homebrew/homebrew-bundle

# specify a directory to install
cask_args appdir: '/Applications'

# install packages
tap 'caskroom/homebrew-cask' || true
tap 'caskroom/versions' || true

# install packages
brew 'git'
brew 'tree'
brew 'python'
brew 'python3'
brew 'vim'
brew 'nvim'
brew 'tmux'
brew 'grv'

# casks
cask 'google-chrome'
cask 'dropbox'
cask 'alfred'
cask 'evernote'
cask 'skype'
cask 'spotify'
cask '1password'
cask 'dash'
cask 'alacritty'
cask 'istat-menus'
cask 'discord'
cask 'slack'
cask 'libreoffice'
cask 'emacs'
cask 'macvim'
cask 'rowanj-gitx'
cask 'iterm2'

# mac apple store
mas 'Airmail 3', id: 918858936
mas 'Navicat Essentials for PostgreSQL', id: 466725643
mas 'Magnet', id: 441258766

